#!/usr/bin/env python3
"""Generate the checked-in deterministic EFR32 seed and mutation corpus."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import sys

HERE = Path(__file__).resolve().parent
if str(HERE.parent.parent) not in sys.path:
    sys.path.insert(0, str(HERE.parent.parent))

from research.efr32.model import build_plaintext_frame, build_v4_join_body
from research.efr32.mutate import generate


SOURCE = bytes.fromhex("0102030405060708")


def digest(path: Path, base: Path) -> dict[str, object]:
    relative = path.relative_to(base).as_posix()
    description = (
        "Deterministic mutation of the synthetic version-4 join seed"
        if relative.startswith("mutations/")
        else "Deterministic synthetic protocol seed generated by the public model"
    )
    return {
        "path": relative,
        "size": path.stat().st_size,
        "sha256": hashlib.sha256(path.read_bytes()).hexdigest(),
        "classification": "synthetic",
        "description": description,
        "identifiers_sanitized": True,
        "exact_observed": False,
        "physically_validated": False,
        "analytical_only": True,
    }


def build(output: Path) -> None:
    seeds = {
        "seeds/v4-join-normal.bin": build_plaintext_frame(
            7, build_v4_join_body(b"BH61-SEED"), SOURCE, 0
        ),
        "seeds/type4-counter-sync.bin": build_plaintext_frame(
            4, b"\x01\x12\x34", SOURCE, 1
        ),
        "seeds/type11-scan-info.bin": build_plaintext_frame(
            11, b"\x00\x00\x01\x00\x00", SOURCE, 2
        ),
    }
    for relative, content in seeds.items():
        path = output / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(content)
    mutation_root = output / "mutations"
    generated = generate(output / "seeds/v4-join-normal.bin", mutation_root,
                         limit=96, random_seed=0x0B61)
    artifacts = []
    for path in sorted(output.rglob("*.bin")):
        artifacts.append(digest(path, output))
    manifest = {
        "schema": "bh61-efr32-corpus/v1",
        "scope": "offline-only",
        "generator": "research/efr32/generate_corpus.py",
        "mutation_manifest_sha256": hashlib.sha256(
            (mutation_root / "manifest.json").read_bytes()
        ).hexdigest(),
        "case_count": len(generated["cases"]),
        "artifacts": artifacts,
    }
    (output / "manifest.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    build(args.output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
